DECLARE @PO  VARCHAR(30)
DECLARE @LOT VARCHAR(100)
DECLARE @USER VARCHAR(30)
DECLARE @WAREHOUSE VARCHAR(10)
DECLARE @LOCATION VARCHAR(30)
DECLARE @QUANTITY VARCHAR(20)
----------------
SET @PO = 'POVALUE'
SET @LOT ='LOTVALUE'
SET @USER = 'USERVALUE'
SET @WAREHOUSE = 'WAREHOUSEVALUE'
SET @LOCATION ='LOCATIONVALUE'
SET @QUANTITY = 'QUANTITYVALUE'
------------------------------

---AN se xử lý code ở đây


